services:
  web:
    build: .
    ports:
      - "3000:3500"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
      REACT_APP_BACKEND_URL: $REACT_APP_BACKEND_URL
    stdin_open: true
    tty: true
    command: npm start

